apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-only-gateway"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Release.Name }}"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "{{ .Values.gatewayNamespace }}"
          podSelector:
            matchLabels:
              app: gateway
      ports:
        - port: 3000
